### ISSUE TITLE
Errors when using a business account.

### ISSUE THREAD

**Issue by nrb26** [zingz0r/CloudFlare.Client#1]
Getting the message below when trying to query a business account. I assume the same will happen with an Enterprise account.

System.AggregateException: One or more errors occurred. (Exception occurred.) ---> CloudFlare.Client.Exceptions.PersistenceUnavailableException: Exception occurred. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "business" to type 'CloudFlare.Client.Enumerators.LegacyType'. Path 'result[6].plan.legacy_id', line 1, position 11314. ---> System.ArgumentException: Requested value 'business' was not found.

**Comment by zingz0r** [comment]
Ty for your feedback.
Will be fixed in next version soon.

**Comment by zingz0r** [comment]
Fixed by adding missing account types in [0e5f308](https://github.com/zingz0r/CloudFlare.Client/commit/0e5f30873ca8f35a130dfc27157ffc37e2112ef9)

**Comment by nrb26** [comment]
Works great thanks.
