### ISSUE TITLE
API Token support

### ISSUE THREAD

**Issue by se** [zingz0r/CloudFlare.Client#10]
Hi @zingz0r,

I started to develop API Token support (almost finished BTW). I'm gonna send PR today.

If you are already doing that, please let me know.

**Comment by zingz0r** [comment]
Hi,
Sorry but I'm on vacation.I can only check your PR after 20. August  :S

**Comment by alexjamesbrown** [comment]
Did this get merged? API Token Support, rather than global API key?

**Comment by alexjamesbrown** [comment]
Sorry, ignore me! Yes it has

` var cloudflareClient = new CloudFlareClient(new ApiTokenAuthentication("CloudflareApiToken_Goes_Here"));`
