### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by jwu-au** [zingz0r/CloudFlare.Client#19]
Hi @zingz0r ,

Just come to the license of this great library, we want to use it in one of our services. But it seems it is restricted by the license. I wonder what way we can use it commercially? Or is it possible to change to MIT license? 

Thank you,
Jing

**Comment by zingz0r** [comment]
Hi @jwu-au,

contact me via email on zingz0r@tothnet.hu to discuss your case.

Best regards.

**Comment by tinohager** [comment]
@zingz0r I would also be interested in the reason for the license chosen.

**Comment by zingz0r** [comment]
I'll consider changing the license

**Comment by zingz0r** [comment]
FYI:
https://github.com/zingz0r/CloudFlare.Client/blob/master/LICENSE
