### ISSUE TITLE
[Bug] ResultInfo is Not Being Populated on Responses

### ISSUE THREAD

**Issue by kyleherzog** [zingz0r/CloudFlare.Client#45]
**Describe the bug**
When getting a response back from a call to `client.Zones.GetAsync()`, the response object does not populate the `ResultInfo` property.  The property remains null.

**Versions**
- CloudfFare.Client NuGet version = 5.0.1
- Project target framework = net50

**To Reproduce**
1. Create CloudFlareClient with API Token authentication
2. Call `client.Zones.GetAsync()` method
4. The `CloudFlareResult<IReadOnlyList<Zone>>` object has a null ResultInfo property.

**Expected behavior**
The `ResultInfo` property should be populated with the result info returned from Cloudflare.  I can see the info being returned if I inspect the HTTP traffic.

**Additional context**
The account I'm querying has over 250 zones.  I'm trying to page them with a page size of 100.  So, I need the `ResultInfo` property filled out to know if there are more results to be requested.

**Comment by zingz0r** [comment]
Fixed in 6.0.0
