### ISSUE TITLE
[Bug] Invalid header

### ISSUE THREAD

**Issue by BinaryAssault** [zingz0r/CloudFlare.Client#51]
**Describe the bug**
Using the example in the readme with my own email/key, I get an Invalid format for X-Auth-Key header

**Versions**
- CloudfFare.Client NuGet version:  6.0.1 stable
- Your project target framework: .NET 6.0

**To Reproduce**
1. Create CloudFlareClient using the example in the readme
2. Run the application
3. See the error

**Expected behavior**
Headers aren't incorrect

**Additional context**
NA

**Comment by BinaryAssault** [comment]
![image](https://user-images.githubusercontent.com/19739224/158719487-9defb15f-91ec-4ed8-8704-5d82b3aca333.png)

**Comment by zingz0r** [comment]
The authentication is working as expected. 
You should use the Global API Key for for API key based authentication
![image](https://user-images.githubusercontent.com/4019336/166197458-f7355674-bc45-4dce-b948-2b42ea552307.png)
or you should create a token for Token-based authentication
![image](https://user-images.githubusercontent.com/4019336/166197568-9ecc8258-d5fd-4f00-80da-1f997c1332dc.png)
