### ISSUE TITLE
404 when calling CustomHostnames.GetAsync

### ISSUE THREAD

**Issue by haimbell** [zingz0r/CloudFlare.Client#55]
**Describe the bug**
CustomHostnames.GetAsync will throw an exception when using filter

**Versions**
- CloudfFare.Client NuGet version 6.1.1
- Your project target framework .net 6

**To Reproduce**
1. Create CloudFlareClient with apiToken authentication
2. Call 'CustomHostnames.GetAsync ' method with filters 
4. See the error

**Expected behavior**
Get a valid json result from cloudflare

**Additional context**
removing '/' from CustomHostnames.cs line 57 will resolve the bug

**Comment by zingz0r** [comment]
Will be fixed in next release (6.1.2)
