### ISSUE TITLE
MethodType.Txt is missing

### ISSUE THREAD

**Issue by haimbell** [zingz0r/CloudFlare.Client#56]
**Describe the bug**
call CustomHostnames.GetAsync will result in an exception when TXT record when presented.

JsonSerializationException: Error converting value "txt" to type 'CloudFlare.Client.Enumerators.MethodType'. Path 'result[2].ssl.method', line 81, position 23.

**Versions**
- CloudfFare.Client NuGet version 6.1.1
- Your project target framework .net 6

**To Reproduce**
1. Create CloudFlareClient with 'apiToken' authentication
2. Call 'CustomHostnames.GetAsync' method
4. See the error

**Expected behavior**
valid CloudflareResult

**Additional context**

**Comment by haimbell** [comment]
a sample response from Cloudfalre API

`{
    "result": [
        {
            "id": "969619ad-d664-4879-9ef1-369b13c6ce91",
            "hostname": "go.example,com",
            "ssl": {
                "id": "8ecabc16-290d-429b-918c-3813b9fb198f",
                "type": "dv",
                "method": "cname",
                "status": "pending_validation",
                "cname": "_ca3-7202296226154bc39e6fae300e2c6962.go.example,com",
                "cname_target": "dcv.digicert.com",
                "validation_records": [
                    {
                        "status": "pending",
                        "cname": "_ca3-7202296226154bc39e6fae300e2c6962.go.example,com",
                        "cname_target": "dcv.digicert.com"
                    }
                ],
                "bundle_method": "ubiquitous",
                "wildcard": false,
                "certificate_authority": "digicert"
            },
            "status": "pending",
            "verification_errors": [
                "custom hostname does not CNAME to this zone."
            ],
            "ownership_verification": {
                "type": "**txt**",
                "name": "_cf-custom-hostname.go.example,com",
                "value": "45060627-96b0-4172-9df0-ab1491b7be21"
            },
            "ownership_verification_http": {
                "http_url": "http://go.example,com.well-known/cf-custom-hostname-challenge/969619ad-d664-4879-9ef1-369b13c6ce91",
                "http_body": "45060627-96b0-4172-9df0-ab1491b7be21"
            },
            "created_at": "2022-05-14T12:41:21.529637Z"
        }
    ],
    "result_info": {
        "page": 1,
        "per_page": 20,
        "count": 1,
        "total_count": 1,
        "total_pages": 1
    },
    "success": true,
    "errors": [],
    "messages": []
}`

**Comment by zingz0r** [comment]
It will be fixed in the next release (6.1.2)
