### ISSUE TITLE
[Bug] DNS filter "Match" doesn't match API

### ISSUE THREAD

**Issue by Eonasdan** [zingz0r/CloudFlare.Client#66]
**Describe the bug**
According to the [CloudFlare API docs](https://api.cloudflare.com/#dns-records-for-a-zone-list-dns-records) "match" is a string and should either have the value of "any" or "all"

**Versions**
- CloudfFare.Client NuGet version = 6.1.2
- Your project target framework = 6

**To Reproduce**
1. Create CloudFlareClient with tokenauthentication
2. `client.Zones.DnsRecords.GetAsync` with a `DnsRecordFilter` where Match is true
4. This will result have an API error.

**Expected behavior**
No error :)

**Additional context**
Changing this line seems to fix it. It might be worth renaming or at least updating the xml docs on how this works.

`.InsertValue(Filtering.Match, (filter?.Match ?? false) ? "all" : "any");`

**Comment by zingz0r** [comment]
Fixed in: #68. Thanks to @hectorchec
