### ISSUE TITLE
Unable to import zone file through ImportAsync, but the same DNS file imports through the CloudFlare API

### ISSUE THREAD

**Issue by carsonatxencall** [zingz0r/CloudFlare.Client#67]
When trying to upload via the `ImportAsync` method, I get the following error:

> Failed to parse form data. Make sure the Content-Type is multipart/form-data.

This is the code: `var records = await client.Zones.DnsRecords.ImportAsync(zoneId, importFile, false);`

I opened the file with a `StreamReader` and it was able to read the contents, so I know the code can get the contents, here's a sample snippet of the file contents
![image](https://user-images.githubusercontent.com/69700040/190046315-81a4570c-d8e1-43fa-891b-038f6165e353.png)

When uploading through the UI, it works fine, for the `ImportAsync` it fails with that error and I'm not how else to troubleshoot as I have no other information.

Everything else works fine (i.e. I can Add/Delete records, get records, get the zone etc. etc.).

As a separate note, after successfully uploading to CloudFlare using the UI, I then downloaded the export file, and tried importing that, and it failed with the same error.

**Comment by zingz0r** [comment]
Fix will be available in the next version 6.1.3
