### ISSUE TITLE
[Bug] Zones.DnsRecords.UpdateAsync Erases Existing comments and doesn't provide the functionality to set a comment

### ISSUE THREAD

**Issue by MetUys** [zingz0r/CloudFlare.Client#93]
**Describe the bug**
Using the "Zones.DnsRecords.UpdateAsync" it erases the existing comment for the DNS record.
It also does no expose a property to set the comment either.

**Versions**
- CloudfFare.Client NuGet v6.3
- dotnet6

**Location**
[CloudFlare.Client]/[Api]/[Zones]/[DnsRecord]/ModifiedDnsRecord.cs

**Expected behavior**
the ModifiedDnsRecord should contain a property for "comment".
- Not setting a comment property value should allow the existing comment to be kept,
- To Update a comment the property value should contain the new comment string,
- To Remove a comment the property value should be set as blank/null.

**Comment by zingz0r** [comment]
Fixed in: #93 . Thanks to @Steffaanus 
Fix will be available in the next version 8.0.0
